DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS courses CASCADE;

DROP TABLE IF EXISTS subjects CASCADE;

DROP TABLE IF EXISTS course_subject CASCADE;

DROP TABLE IF EXISTS roles CASCADE;

DROP TABLE IF EXISTS staff CASCADE;

DROP TABLE IF EXISTS course_subject_staff CASCADE;

DROP TABLE IF EXISTS modules CASCADE;

DROP TABLE IF EXISTS lessons CASCADE;

DROP TABLE IF EXISTS file_type CASCADE;

DROP TABLE IF EXISTS attachments CASCADE;

DROP TABLE IF EXISTS lesson_attachment CASCADE;

DROP TABLE IF EXISTS module_attachment CASCADE;

DROP TABLE IF EXISTS exercises CASCADE;

DROP TABLE IF EXISTS questions CASCADE;

DROP TABLE IF EXISTS exercise_question CASCADE;

DROP TABLE IF EXISTS available_question_answers CASCADE;

DROP TABLE IF EXISTS lesson_exercise CASCADE;

DROP TABLE IF EXISTS module_exercise CASCADE;

CREATE TABLE users
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	public_id UUID DEFAULT gen_random_uuid() NOT NULL,
	
	login VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	
	active BOOLEAN NOT NULL DEFAULT TRUE,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE users ADD CONSTRAINT pk_users PRIMARY KEY (id);

CREATE TABLE courses
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	public_id UUID DEFAULT gen_random_uuid() NOT NULL,
	
	title VARCHAR(256) NOT NULL UNIQUE,
	description VARCHAR NOT NULL,
	author_id bigint NOT NULL,
	
	active BOOLEAN NOT NULL DEFAULT TRUE,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE courses ADD CONSTRAINT pk_courses PRIMARY KEY (id);

CREATE TABLE subjects
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	public_id UUID DEFAULT gen_random_uuid() NOT NULL,
	
	name varchar(128) NOT NULL UNIQUE,
	
	active BOOLEAN NOT NULL DEFAULT TRUE,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE subjects ADD CONSTRAINT pk_subjects PRIMARY KEY (id);

CREATE TABLE course_subject
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	
	course_id bigint NOT NULL,
	subject_id bigint NOT NULL,
	
	active BOOLEAN NOT NULL DEFAULT TRUE,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE course_subject ADD CONSTRAINT pk_course_subject PRIMARY KEY (id);

ALTER TABLE course_subject ADD UNIQUE (course_id,
subject_id);

CREATE TABLE roles(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	
	name varchar(64) NOT NULL UNIQUE
);

ALTER TABLE roles ADD CONSTRAINT pk_roles PRIMARY KEY (id);

CREATE TABLE staff
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	public_id UUID DEFAULT gen_random_uuid() NOT NULL,
	
	user_id bigint NOT NULL,
	role_id bigint NOT NULL,
	
	active boolean NOT NULL DEFAULT TRUE,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE staff ADD CONSTRAINT pk_staff PRIMARY KEY (id);

ALTER TABLE staff ADD CONSTRAINT fk_staff_user_id FOREIGN KEY (user_id) REFERENCES users;

ALTER TABLE staff ADD CONSTRAINT fk_staff_role_id FOREIGN KEY (role_id) REFERENCES roles;

CREATE TABLE course_subject_staff
(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	
	course_subject_id bigint NOT NULL,
	staff_id bigint NOT NULL,
	role_id bigint NOT NULL,

	active BOOLEAN NOT NULL DEFAULT TRUE,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE course_subject_staff ADD CONSTRAINT pk_course_subject_staff PRIMARY KEY(id);

ALTER TABLE course_subject_staff ADD CONSTRAINT fk_course_subject_staff_course_subject_id FOREIGN KEY (course_subject_id) REFERENCES course_subject;

ALTER TABLE course_subject_staff ADD CONSTRAINT fk_course_subject_staff_staff_id FOREIGN KEY (staff_id) REFERENCES staff;

ALTER TABLE course_subject_staff ADD CONSTRAINT fk_course_subject_staff_role_id FOREIGN KEY(role_id) REFERENCES roles;

CREATE TABLE modules (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	public_id UUID DEFAULT gen_random_uuid() NOT NULL,
	
	"number" float NOT NULL,
	title varchar(256) NOT NULL,
	"content" varchar NOT NULL,
	teacher_id bigint NOT NULL,
	subject_id bigint NOT NULL,

	active BOOLEAN DEFAULT TRUE NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE modules ADD CONSTRAINT pk_modules PRIMARY KEY(id);

ALTER TABLE modules ADD CONSTRAINT fk_modules_teacher_id FOREIGN KEY (teacher_id) REFERENCES staff;

ALTER TABLE modules ADD CONSTRAINT fk_modules_subject_id FOREIGN KEY (subject_id) REFERENCES subjects;

CREATE TABLE lessons(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	public_id UUID DEFAULT gen_random_uuid() NOT NULL,
	
	"number" float NOT NULL,
	title varchar(256) NOT NULL,
	"content" varchar NOT NULL,
	module_id bigint NOT NULL,
	teacher_id bigint NOT NULL,

	active BOOLEAN DEFAULT TRUE NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE lessons ADD CONSTRAINT pk_lessons PRIMARY KEY(id);

ALTER TABLE lessons ADD CONSTRAINT fk_lessons_module_id FOREIGN KEY (module_id) REFERENCES modules;

ALTER TABLE lessons ADD CONSTRAINT fk_lessons_teacher_id FOREIGN KEY (teacher_id) REFERENCES staff;

CREATE TABLE file_type(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar NOT NULL UNIQUE
);

ALTER TABLE file_type ADD CONSTRAINT pk_file_type PRIMARY KEY(id);

CREATE TABLE attachments(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	public_id UUID DEFAULT gen_random_uuid() NOT NULL,
	
	title varchar(256) NOT NULL,
	description varchar(512) NOT NULL,
	file_size float NOT NULL,
	file_path varchar NOT NULL,
	file_name varchar NOT NULL,	
	file_type_id bigint NOT NULL,

	uploaded_by bigint NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE attachments ADD CONSTRAINT pk_attachments PRIMARY KEY(id);

ALTER TABLE attachments ADD CONSTRAINT fk_attachments_file_type_id FOREIGN KEY(file_type_id) REFERENCES file_type;

ALTER TABLE attachments ADD CONSTRAINT fk_attachments_uploaded_by FOREIGN KEY(uploaded_by) REFERENCES users;

CREATE TABLE lesson_attachment(
	lesson_id bigint NOT NULL,
	attachment_id bigint NOT NULL
);

ALTER TABLE lesson_attachment ADD UNIQUE (lesson_id,
attachment_id);

ALTER TABLE lesson_attachment ADD CONSTRAINT fk_lesson_attachment_lesson_id FOREIGN KEY(lesson_id) REFERENCES lessons;

ALTER TABLE lesson_attachment ADD CONSTRAINT fk_lesson_attachment_attachment_id FOREIGN KEY(attachment_id) REFERENCES attachments;

CREATE TABLE module_attachment(
	module_id bigint NOT NULL,
	attachment_id bigint NOT NULL
);

ALTER TABLE module_attachment ADD UNIQUE(module_id,
attachment_id);

ALTER TABLE module_attachment ADD CONSTRAINT fk_module_attachment_module_id FOREIGN KEY(module_id) REFERENCES modules;

ALTER TABLE module_attachment ADD CONSTRAINT fk_module_attachment_attachment_id FOREIGN KEY(attachment_id) REFERENCES attachments;
 
CREATE TABLE exercises(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	public_id UUID DEFAULT gen_random_uuid() NOT NULL,
	
	"number" float NOT NULL,
	value float NOT NULL,
	height float NOT NULL,
	available_from timestamp NOT NULL,
	available_until timestamp NOT NULL,

	created_by bigint NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE exercises ADD CONSTRAINT pk_exercises PRIMARY KEY(id);

ALTER TABLE exercises ADD CONSTRAINT fk_exercises_created_by FOREIGN KEY(created_by) REFERENCES users;

CREATE TABLE questions(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar NOT NULL
);

ALTER TABLE questions ADD CONSTRAINT pk_questions PRIMARY KEY(id);

ALTER TABLE questions ADD UNIQUE(name);

CREATE TABLE exercise_question(
	question_id bigint NOT NULL,
	exercise_id bigint NOT NULL
);

ALTER TABLE exercise_question ADD UNIQUE(question_id,
exercise_id);

ALTER TABLE exercise_question ADD CONSTRAINT fk_exercise_question FOREIGN KEY(question_id) REFERENCES questions;

ALTER TABLE exercise_question ADD CONSTRAINT fk_exercise_exercise FOREIGN KEY(exercise_id) REFERENCES exercises;

CREATE TABLE available_question_answers(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	
	answer varchar NOT NULL,
	correct boolean NOT NULL,
	question_id bigint NOT NULL
);

ALTER TABLE available_question_answers ADD CONSTRAINT pk_available_question_answers PRIMARY KEY(id);

ALTER TABLE available_question_answers ADD CONSTRAINT dk_available_question_answers_question_id FOREIGN KEY(question_id) REFERENCES questions;

CREATE TABLE lesson_exercise(
	lesson_id bigint NOT NULL,
	exercise_id bigint NOT NULL
);

ALTER TABLE lesson_exercise ADD UNIQUE(lesson_id,
exercise_id);

ALTER TABLE lesson_exercise ADD CONSTRAINT fk_lesson_exercise_lesson_id FOREIGN KEY (lesson_id) REFERENCES lessons;

ALTER TABLE lesson_exercise ADD CONSTRAINT fk_lesson_exercise_exercise_id FOREIGN KEY(exercise_id) REFERENCES exercises;

CREATE TABLE module_exercise(
	module_id bigint NOT NULL,
	exercise_id bigint NOT NULL
);

ALTER TABLE module_exercise ADD UNIQUE(module_id,
exercise_id);

ALTER TABLE module_exercise ADD CONSTRAINT fk_module_exercise_module_id FOREIGN KEY(module_id) REFERENCES modules;

ALTER TABLE module_exercise ADD CONSTRAINT fk_module_exercise_exercise_id FOREIGN KEY(exercise_id) REFERENCES exercises;

/* seeds.sql */

INSERT
	INTO
	roles(name)
VALUES
('INSTRUCTOR'),
('TEACHER'),
('SUPPORT'),
('ADMIN'),
('TUTOR');

